## Funciones aleatorias
Ya que estamos repasando funciones no podemos olvidar las funciones aleatorias de Numpy, encontradas en el módulo random.

[En este enlace a la documentación oficial](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html) encontraréis el listado completo con ejemplos de uso. 

Tenemos funciones para generar arrays con **datos aleatorios** y **permutaciones**. También hay muchas enfocadas a generar muestras de distribuciones de probabilidadpensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

### Datos aleatorios

In [175]:
import numpy as np

# Número decimal entre 0 y 1
np.random.rand()

0.3334229786160372

In [176]:
# Array 1D de decimales entre 0 y 1
np.random.rand(4)

array([ 0.98037833,  0.68852893,  0.94593868,  0.79645589])

In [177]:
# Array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[ 0.9514949 ,  0.91115546],
       [ 0.07018065,  0.76570926],
       [ 0.96519048,  0.02009274],
       [ 0.65534272,  0.79159674]])

In [188]:
# Array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[ 8.61778202,  6.81368708],
        [ 7.99862719,  3.64448439]],

       [[ 7.11681674,  8.11517456],
        [ 5.29141264,  3.27754127]]])

In [189]:
# Array 4D de decimales entre -N y M
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[ 5.94066981, -6.10081435],
         [-4.85375846,  4.51694499]],

        [[ 3.1264627 , -8.57035636],
         [ 4.71590752,  8.51147178]]],


       [[[ 9.83840494,  8.51724141],
         [ 0.59540768, -0.44959352]],

        [[-4.82373399,  4.13123614],
         [-4.25213011, -0.60892714]]]])

In [179]:
# Número entero entre 0 y N
np.random.randint(10)

9

In [180]:
# Array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[8, 4],
       [7, 4],
       [0, 0]])

In [181]:
# Array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[ 9, -7],
       [ 5,  4],
       [ 7,  7]])

### Permutaciones

In [182]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
# Desordenar un array (lo cambia)
np.random.shuffle(arr)
arr

array([3, 0, 6, 4, 7, 5, 1, 9, 8, 2])

In [184]:
# Generar secuencia permutada a partir de un array (no lo cambia)
np.random.permutation(arr)

array([9, 4, 0, 3, 6, 1, 7, 8, 5, 2])

In [185]:
arr

array([3, 0, 6, 4, 7, 5, 1, 9, 8, 2])

## Ejercicios